from .err import *
from .netif import *
from .pbuf import *


AF_UNSPEC = 0
AF_INET = 2
AF_INET6 = 10
PF_INET = AF_INET
PF_INET6 = AF_INET6
PF_UNSPEC = AF_UNSPEC

IPPROTO_IP = 0
IPPROTO_ICMP = 1
IPPROTO_TCP = 6
IPPROTO_UDP = 17
IPPROTO_IPV6 = 41
IPPROTO_ICMPV6 = 58
IPPROTO_UDPLITE = 136
IPPROTO_RAW = 255

MSG_PEEK = 0x01
MSG_WAITALL = 0x02
MSG_OOB = 0x04
MSG_DONTWAIT = 0x08
MSG_MORE = 0x10
MSG_NOSIGNAL = 0x20

SOCK_STREAM = 1
SOCK_DGRAM = 2
SOCK_RAW = 3

INADDR_ANY = bytes(4)
